### ISSUE TITLE
src folder seems to be missing

### ISSUE THREAD

**Issue by tedhuntington** [mongoose-os-libs/ota-common#1]
getting: 
Error: /go/src/cesanta.com/mos/manifest_parser/manifest_parser.go:311: neither sources nor prebuilt binary exists for the lib "ota-common" (or, if a library doesn't have any code by design, its mos.yml shouldn't contain "sources"). Fetch error was: [got 404 status code when accessed https://github.com/mongoose-os-libs/ota-common/releases/download/latest/libota-common-esp32.a]

**Comment by rojer** [comment]
this is a closed library. there was an issue with publishing binaries which has now been resolved.
